server:
  port: 8001
spring:
  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  redis:
    host: 192.168.200.100
    password: Lfy123456
  zipkin:
    base-url: http://192.168.200.100:9411/
    sender:
      type: web

app:
  thread-pool:
    core: 4
    max: 8
    queue-size: 2000
    keep-alive-time: 300

aaa: 123

#暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"