server:
  port: 9000
  tomcat:
    max-connections: 200 #我们的内存支持不了8000连接


#数据源配置好
spring:
  zipkin:
    base-url: http://192.168.200.100:9411/
    sender:
      type: web
  datasource:
    url: jdbc:mysql://192.168.200.100:3306/gmall_product?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.200.100
    password: Lfy123456

#自定义配置
app:
  minio:
    endpoint: http://192.168.200.100:9000
    ak: admin
    sk: admin123456
    bucket-name: gmall
  thread-pool:
    core: 4
    max: 8